name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Test import (debug)
      run: |
        python -c "import PyQt5; print('PyQt5 OK')"
        python -c "import pysubs2; print('pysubs2 OK')"
        python -c "import requests; print('requests OK')"
        python -c "import opencc; print('opencc OK')"
        

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "SrtToAssConverter" --hidden-import=opencc --hidden-import=pysubs2 --hidden-import=requests --collect-all=opencc toAss_standard_qt.py
        
    - name: Test executable exists
      run: |
        echo "Checking dist directory contents:"
        dir dist
        echo "Checking if executable exists:"
        if (Test-Path "dist/SrtToAssConverter.exe") {
          echo "✓ Executable created successfully"
          $size = (Get-Item "dist/SrtToAssConverter.exe").Length
          echo "File size: $($size / 1MB) MB"
        } else {
          echo "✗ Executable not found"
          echo "Available files in dist:"
          Get-ChildItem dist -Recurse
          exit 1
        }
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SrtToAssConverter-Windows
        path: dist/SrtToAssConverter.exe
